#################################################### Libraries ####################################################


#install.packages("drat", repos="https://cran.rstudio.com")
#install.packages("xgboost", repos="https://cran.rstudio.com")
#install.packages("tidyverse", repos="https://cran.rstudio.com")
#install.packages("microbenchmark", repos="https://cran.rstudio.com")
#install.packages("pROC", repos="https://cran.rstudio.com")
#install.packages("class", repos="https://cran.rstudio.com")
#install.packages("caret", repos = "http://cran.us.r-project.org")
#install.packages("plotROC", repos = "http://cran.us.r-project.org")
#install.packages("ggplot2", repos = "http://cran.us.r-project.org")
#install.packages("reshape2", repos = "http://cran.us.r-project.org")
#install.packages("DMwR", repos = "http://cran.us.r-project.org")
#install.packages("PRROC", repos = "http://cran.us.r-project.org")
#install.packages("gmodels", repos = "http://cran.us.r-project.org") 
#install.packages("rpart", repos = "http://cran.us.r-project.org") 
#install.packages("installr", repos = "http://cran.us.r-project.org")
#install.packages("caTools", repos = "http://cran.us.r-project.org") 
#install.packages("plyr", repos = "http://cran.us.r-project.org")
#install.packages("e1071", repos = "http://cran.us.r-project.org")
#install.packages("DMwR", repos = "http://cran.us.r-project.org")
#install.packages("rsconnect", repos = "http://cran.us.r-project.org")
#install.packages("kernlab", repos = "http://cran.us.r-project.org")

library(kernlab)
library(pROC)
library(ROCR)
library(microbenchmark)
library(caret)
library(plotROC)
library(ggplot2)
library(reshape2)
library(DMwR)
library(PRROC)
library(gmodels)
library(rpart)
library(installr)
library(caTools)
library(plyr)
library(e1071)
library(pROC)
library(tidyverse)
library(xgboost)
library(caret)
library(class)
library(DMwR)



library(shiny)
library(rsconnect)

