---
output:
  html_document: 
    df_print: kable
  pdf_document: default
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(stargazer)
knitr::opts_chunk$set(echo = TRUE)
```

# **Support Vector Machine - Project**

Work done by Elie PICAUD and Loïc PALMA for the Spring 2019 class of Big Data Analytics: Support Vector Machine at ESA Master's degree. The instructor was [Christophe Hurlin](https://www.univ-orleans.fr/deg/masters/ESA/CH/churlin.htm).

The datasets used in this project is **FREE** and can be found [here](https://www.kaggle.com/mlg-ulb/creditcardfraud).


## Content

The datasets contains transactions made by credit cards in September 2013 by european cardholders. This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, ... V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

## Acknowledgements

The dataset has been collected and analysed during a research collaboration of Worldline and the [Machine Learning Group](http://mlg.ulb.ac.be) of ULB (Université Libre de Bruxelles) on big data mining and fraud detection. More details on current and past projects on related topics are available on [researchgate](https://www.researchgate.net/project/Fraud-detection-5) and the page of the DefeatFraud project.










[Master ESA](https://www.univ-orleans.fr/deg/masters/ESA/index.htm)

[Github](https://github.com/loicpalma/Shiny_App)

